local algotest = require("algotest")
print(algotest.makeAccount())
txn, contractAddr = algotest.createAppFromConfig("AAAAA","contract1")
print(txn)
print(contractAddr)
-- print(algotest.createAppFromConfig("AAAAA","contract2"))
algotest.startPrivateNetwork()
sender=txn:submit()
print("txn sender:", sender)