local algotest = require("algotest")
acct1=algotest.makeAccount()
print("acct1: ", acct1)
txn, contractAddr = algotest.createAppFromConfig(acct1,"contract1")
print("contract addr: ",contractAddr)
-- print(algotest.createAppFromConfig("AAAAA","contract2"))
print("starting private network")
algotest.startPrivateNetwork()
txid=txn:submit("533e921d0920c6f82d2874daefa70f76")
print("submitted txn id:", txid)